data:
  container_name: data
  build: data

galaxy:
  container_name: galaxy
  build: galaxy
  volumes_from:
    - data
  environment:
    VIRTUAL_HOST: galaxy.central-function.ccc.dev
    VIRTUAL_PORT: 8080
  ports:
    - 8080:8080

nginx:
  container_name: nginx
  image: jwilder/nginx-proxy
  ports:
    - 80:80
  environment:
    DOCKER_HOST:
    DOCKER_TLS_VERIFY:
    DOCKER_CERT_PATH:
  volumes:
    - ${DOCKER_CERT_PATH}:${DOCKER_CERT_PATH}
